FROM python:3.8-slim-buster

RUN mkdir /mysite
WORKDIR /mysite
RUN pip install --upgrade pip
COPY requirements.txt /mysite/

RUN pip install -r requirements.txt
COPY . /mysite/

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]